export enum IconListEnum {
  Share = 'share',
  ViewReport = 'view-report',
  Calendar = 'calendar',
  Target = 'target',
  HandGiving = 'hand-giving',
  ThumbsUp = 'thumbs-up',
  Dot = 'dot',
  Deactivate = 'deactivate',
  Activate = 'activate',
  Plus = 'plus',
  Edit = 'edit',
  Delete = 'delete',
  Eye = 'eye',
  ArrowBack = 'arrow-back',
  Submit = 'submit',
  User = 'user',
  HeadPhones = 'head-phones',
  Faq = 'faq',
  Text = 'text',
  ChevronRight = 'chevron-right',
  Activity = 'activity',
  ChartUpward = 'chart-upward',
  Folder = 'folder',
  Users = 'users',
}
